CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  description TEXT NOT NULL,
  created TIMESTAMP NOT NULL,
  done BOOLEAN DEFAULT FALSE,
  user_id int REFERENCES users(id)
)
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);